/** Source of the OpenCode plugin written by `agentlink install opencode`. */
export function openCodePluginSource(socketPath: string): string {
  return `// agentlink plugin for OpenCode (generated by \`agentlink install opencode\`; safe to delete).
// Reports session busy/idle to the agentlink daemon and delivers messages from other agents
// with client.session.promptAsync (noReply for FYI messages, so they cost no tokens).
import { readFileSync } from "node:fs";
import { request } from "node:http";

const SOCKET = ${JSON.stringify(socketPath)};

function call(method, path, body, timeoutMs = 5000) {
  const payload = body === undefined ? undefined : JSON.stringify(body);
  return new Promise((resolve, reject) => {
    const req = request(
      {
        socketPath: SOCKET,
        path,
        method,
        headers: { "content-type": "application/json", ...(payload ? { "content-length": Buffer.byteLength(payload) } : {}) },
      },
      (res) => {
        let text = "";
        res.setEncoding("utf8");
        res.on("data", (c) => (text += c));
        res.on("end", () => {
          try {
            const data = text ? JSON.parse(text) : {};
            (res.statusCode ?? 500) >= 400 ? reject(new Error(data?.error?.message ?? String(res.statusCode))) : resolve(data);
          } catch (error) {
            reject(error);
          }
        });
      },
    );
    req.setTimeout(timeoutMs, () => req.destroy(new Error("timeout")));
    req.on("error", reject);
    if (payload) req.write(payload);
    req.end();
  });
}

function selfChain() {
  let start;
  try {
    const stat = readFileSync("/proc/self/stat", "utf8");
    start = stat.slice(stat.lastIndexOf(")") + 2).split(" ")[19];
  } catch {}
  return [
    { pid: 1, ppid: 1, cmd: ["agentlink-opencode-plugin"] },
    { pid: process.pid, ppid: process.ppid, ...(start ? { start } : {}), cmd: ["opencode"] },
  ];
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

export const AgentLink = async ({ client, directory }) => {
  let agentId;
  let sessionId;
  let polling = false;

  const hook = async (event) => {
    const res = await call("POST", \`/v1/hooks/opencode/\${event}\`, {
      payload: { session_id: sessionId, cwd: directory },
      chain: selfChain(),
      env: { cwd: directory },
    });
    if (res?.env?.AGENTLINK_AGENT) agentId = res.env.AGENTLINK_AGENT;
    return res;
  };

  const pollLoop = async () => {
    if (polling) return;
    polling = true;
    while (true) {
      try {
        if (!agentId) await hook("session-start");
        const { push } = await call("GET", \`/v1/adapters/opencode/poll?agent=\${agentId}&timeoutMs=25000\`, undefined, 35000);
        if (!push) continue;
        let ok = false;
        if (sessionId) {
          try {
            await client.session.promptAsync({
              path: { id: sessionId },
              body: { noReply: !push.reply, parts: [{ type: "text", text: push.text }] },
            });
            ok = true;
          } catch {}
        }
        await call("POST", "/v1/adapters/opencode/ack", { token: push.token, ok }).catch(() => {});
      } catch {
        agentId = undefined;
        await sleep(5000);
      }
    }
  };

  return {
    event: async ({ event }) => {
      const props = event?.properties ?? {};
      const sid = props.sessionID ?? props.info?.sessionID ?? (event.type === "session.created" ? props.info?.id : undefined);
      if (sid && sid !== sessionId) {
        sessionId = sid;
        hook("session-start").then(() => pollLoop()).catch(() => {});
      }
      if (event.type === "session.status") {
        const status = props.status?.type;
        if (status === "busy") hook("prompt-submit").catch(() => {});
        if (status === "idle") hook("turn-complete").catch(() => {});
      }
    },
  };
};
`;
}
